version: '3.8'

services:

  mongo:
    image: mongo:6.0.2
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/data:/data/db
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/
    ports:
      - 8000:8000
