name: 'build docker image'
description: 'build docker image'
inputs:
  docker_hub_token:  # id of input
    description: 'docker hub token'
    required: true
  docker_hub_user:
    description: 'docker hub user'
    required: true
  image_name:
    description: 'image name'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo ${{ inputs.docker_hub_token }} > password.txt
        cat password.txt | docker login --username ${{ inputs.docker_hub_user}} --password-stdin
        docker image build -t ${{ inputs.docker_hub_user}}/${{ inputs.image_name }} .
        docker image push ${{ inputs.docker_hub_user}}/${{ inputs.image_name }}
      shell: bash