name: build-docker-image
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_HUB_USER: xiaopeng163

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker login
        run: |
          echo $DOCKER_HUB_TOKEN > password.txt
          cat password.txt | docker login --username $DOCKER_HUB_USER --password-stdin
      - name: build image
        run: |
          docker image build -t $DOCKER_HUB_USER/fastapi-demo:latest .
      - name: push image
        run: |
          docker image push $DOCKER_HUB_USER/fastapi-demo:latest
