name: build-docker-image
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        uses: xiaopeng163/github-action-docker@master
        with:
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
          image_name: fastapi-mongo-demo:latest