name: testing
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    runs-on: ubuntu-22.04
    container: python:3.8-slim
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
    services:
      mongo:
        image: mongo:6.0.2
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   name: set up py
      #   with:
      #     python-version: 3.8
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        id: run-py-test
        run: pytest